//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickEV_Website.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailKomunita
    {
        public int IdKomunitas { get; set; }
        public int IdRelawan { get; set; }
        public System.DateTime TanggalDaftar { get; set; }
    
        public virtual Komunita Komunita { get; set; }
        public virtual Relawan Relawan { get; set; }
    }
}
