//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickEV_Website.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kegiatan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kegiatan()
        {
            this.DetailKegiatans = new HashSet<DetailKegiatan>();
        }
    
        public int IdKegiatan { get; set; }
        public int IdKomunitas { get; set; }
        public string NamaKegiatan { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Lokasi { get; set; }
        public byte[] FotoKegiatan { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime StartRegistration { get; set; }
        public System.DateTime EndRegistration { get; set; }
        public string DescKegiatan { get; set; }
        public string NamaPekerjaan { get; set; }
        public int RelawanDibutuhkan { get; set; }
        public string TugasRelawan { get; set; }
        public string KriteriaRelawan { get; set; }
        public string PerlengkapanRelawan { get; set; }
        public string DomisiliRelawan { get; set; }
        public string FokusEvent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailKegiatan> DetailKegiatans { get; set; }
        public virtual Komunita Komunita { get; set; }
    }
}
